sudo: false

language: node_js
node_js:
  - node
  - lts/*
  - '10'
  - '8'
  - '6'
  - '4'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

before_install:
  - export CC=gcc-7 && CXX=g++-7

script:
  - npm run build
